// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "basicAPI/api/swagger/models"
)

// FindUserOKCode is the HTTP code returned for type FindUserOK
const FindUserOKCode int = 200

/*FindUserOK list of all users

swagger:response findUserOK
*/
type FindUserOK struct {

	/*
	  In: Body
	*/
	Payload []*models.User `json:"body,omitempty"`
}

// NewFindUserOK creates FindUserOK with default headers values
func NewFindUserOK() *FindUserOK {

	return &FindUserOK{}
}

// WithPayload adds the payload to the find user o k response
func (o *FindUserOK) WithPayload(payload []*models.User) *FindUserOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find user o k response
func (o *FindUserOK) SetPayload(payload []*models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindUserOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.User, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*FindUserDefault generic error

swagger:response findUserDefault
*/
type FindUserDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewFindUserDefault creates FindUserDefault with default headers values
func NewFindUserDefault(code int) *FindUserDefault {
	if code <= 0 {
		code = 500
	}

	return &FindUserDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the find user default response
func (o *FindUserDefault) WithStatusCode(code int) *FindUserDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the find user default response
func (o *FindUserDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the find user default response
func (o *FindUserDefault) WithPayload(payload *models.Error) *FindUserDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find user default response
func (o *FindUserDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindUserDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
