// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetSingleUserHandlerFunc turns a function with the right signature into a get single user handler
type GetSingleUserHandlerFunc func(GetSingleUserParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSingleUserHandlerFunc) Handle(params GetSingleUserParams) middleware.Responder {
	return fn(params)
}

// GetSingleUserHandler interface for that can handle valid get single user params
type GetSingleUserHandler interface {
	Handle(GetSingleUserParams) middleware.Responder
}

// NewGetSingleUser creates a new http.Handler for the get single user operation
func NewGetSingleUser(ctx *middleware.Context, handler GetSingleUserHandler) *GetSingleUser {
	return &GetSingleUser{Context: ctx, Handler: handler}
}

/*GetSingleUser swagger:route GET /{id} users getSingleUser

GetSingleUser get single user API

*/
type GetSingleUser struct {
	Context *middleware.Context
	Handler GetSingleUserHandler
}

func (o *GetSingleUser) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetSingleUserParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
